spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: postgres
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    queue:
      queue-name: notification-queue
      exchange-name: notification-exchange
      routing-key: notification.send
