spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: postgres
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
