spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: postgres
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    queue:
      main: notifications.queue
      dlq: notifications.queue.dlq
    exchange:
      main: notifications.exchange
      dlx: notifications.dlx
    routing:
      key: notifications.routingKey
      dlq-key: notifications.dlq.routingKey
